services:
  - type: web
    name: shoora-verse
    env: node
    plan: starter
    buildCommand: NODE_ENV=production npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096 --expose-gc
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_OPTIMIZE_FONTS
        value: "false"
      - key: NEXT_OPTIMIZE_IMAGES
        value: "false"
      - key: NEXT_OPTIMIZE_CSS
        value: "false"
      - key: RENDER_CACHE_DIR
        value: /opt/render/.cache
      - key: NEXT_CACHE_DIR
        value: /opt/render/.cache/next
    disk:
      name: cache
      mountPath: /opt/render/.cache
      sizeGB: 3
    healthCheckPath: /
    autoDeploy: true 