services:
  - type: web
    name: shoora-verse
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
    healthCheckPath: /
    autoDeploy: true 