services:
  - type: web
    name: shoora-verse
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: SKIP_STATIC_GENERATION
        value: "true"
    healthCheckPath: /
    autoDeploy: true 