services:
  - type: web
    name: shoora-verse
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=3072
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_STATIC_BUILD_CONCURRENCY
        value: "1"
      - key: RENDER_CACHE_DIR
        value: /opt/render/.cache
      - key: NEXT_CACHE_DIR
        value: /opt/render/.cache/next
    disk:
      name: cache
      mountPath: /opt/render/.cache
      sizeGB: 2
    healthCheckPath: /
    autoDeploy: true 